/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VHS_Java;

public class Class_Lambda {    
    
    public static void main(String[] arg) {
    	
    	Foo foo = p -> {
    		// Do somethign in function
    		return p + " compage string ";
    		
    	};
    	
    	Compare compare = (a,b)->{
    		
    		return a > b;
    	};
    	
    	
    	
    	UseFoo uf = new UseFoo();
    	
    	String return_s = uf.Add("Something", foo);
    	
    	System.out.println(return_s);
    	
    	Boolean return_check = uf.Checkint(1,2, compare);
    	System.out.println(1);
    	System.out.println(2);
    	System.out.println(return_check);
    	        
    }          
}


class UseFoo{
	
	public String Add(String str, Foo foo ) {	
		return foo.method(str);		
	}
	
	public Boolean Checkint(int a, int b, Compare compare ) {
		
		return !compare.method(a, b);
		
		//return compare.method(a,b);		
	}
}

@FunctionalInterface
interface Foo {
	String method(String string);	
}

@FunctionalInterface
interface Compare {
	Boolean method(int a, int b);	
}

