/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VHS_Java;

public class Library {

    public static void main(String[] arg) {
    	
    	       
    }
    
    
    
}